### ISSUE TITLE
    s_1 = node_idx[topk_indexes[i][0]]     IndexError: list index out of range

### ISSUE THREAD

**Issue by ZhuJD-China** [Whishing/K-NG#1]
(/16T/AIGC/AIGC_env) ubuntu@ubuntu:/16T/AIGC/K-NG$ CUDA_VISIBLE_DEVICES=0 python Konline.py --data_path ../EfficientAD/mvtec_anomaly_detection
/16T/AIGC/AIGC_env/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/16T/AIGC/AIGC_env/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
| feature extraction | train | bottle |:   0%|                                                                                    | 0/21 [00:00<?, ?it/s]
                                                                                                                                                        self.data [[1.0602285  0.34329334 0.         ... 0.         0.         0.9484563 ]                                                 | 0/10 [00:00<?, ?it/s]
 [1.0602285  0.49387696 0.         ... 0.         0.         1.0564817 ]
 [1.0602285  0.41573888 0.         ... 0.         0.         0.8252405 ]
 ...
 [0.         0.         0.         ... 0.09033285 0.         0.        ]
 [0.         0.         0.         ... 0.09033285 0.         0.        ]
 [0.         0.         0.         ... 0.09033285 0.         0.        ]]
dist_matrix tensor([[7.1187, 4.1619, 3.2685,  ..., 4.7151, 1.3020, 6.1182],
        [7.1187, 4.9168, 3.2685,  ..., 4.7151, 1.3020, 6.5026],
        [7.1187, 4.5246, 3.2685,  ..., 4.7151, 1.3020, 5.6915],
        ...,
        [3.9164, 3.6802, 3.2685,  ..., 4.4374, 1.3020, 5.8202],
        [3.9164, 3.6802, 3.2685,  ..., 4.4374, 1.3020, 5.8202],
        [3.9164, 3.6802, 3.2685,  ..., 4.4374, 1.3020, 5.8202]])
topk_indexes tensor([[18, 98],
        [18, 98],
        [18, 98],
        ...,
        [18, 98],
        [18, 98],
        [18, 98]])
| processing data |: 100%|█████████████████████████████████████████████████████████████████████████████████████| 31360/31360 [00:00<00:00, 131303.33it/s]
2
                                                                                                                                                        self.data [[1.0602285  0.34329334 0.         ... 0.         0.         0.9484563 ]                                         | 1/10 [00:00<00:04,  1.95it/s]
 [1.0602285  0.49387696 0.         ... 0.         0.         1.0564817 ]
 [1.0602285  0.41573888 0.         ... 0.         0.         0.8252405 ]
 ...
 [0.         0.         0.         ... 0.09033285 0.         0.        ]
 [0.         0.         0.         ... 0.09033285 0.         0.        ]
 [0.         0.         0.         ... 0.09033285 0.         0.        ]]
dist_matrix tensor([[1.1078, 0.5778, 0.3494,  ..., 0.5455, 0.0556, 0.8435],
        [1.1078, 0.7394, 0.3494,  ..., 0.5455, 0.0556, 0.9296],
        [1.1078, 0.6605, 0.3494,  ..., 0.5455, 0.0556, 0.7332],
        ...,
        [0.5216, 0.3904, 0.3494,  ..., 0.4133, 0.0556, 0.7949],
        [0.5216, 0.3904, 0.3494,  ..., 0.4133, 0.0556, 0.7949],
        [0.5216, 0.3904, 0.3494,  ..., 0.4133, 0.0556, 0.7949]])
topk_indexes tensor([[98, 33],
        [98, 33],
        [98, 26],
        ...,
        [98, 25],
        [98, 25],
        [98, 25]])
| processing data |:   0%|                                                                                                     | 0/31360 [00:00<?, ?it/s]
| epochs |:  10%|██████████▌                                                                                              | 1/10 [00:00<00:04,  1.87it/s]
Traceback (most recent call last):
  File "/16T/AIGC/K-NG/Konline.py", line 419, in <module>
    main()
  File "/16T/AIGC/K-NG/Konline.py", line 151, in main
    kcluster.fit_network()
  File "/16T/AIGC/K-NG/Klink.py", line 78, in fit_network
    s_1 = node_idx[topk_indexes[i][0]]
IndexError: list index out of range

**Comment by Whishing** [comment]
What's your pytorch version? Since the code is written two years ago, some APIs have been changed, please use old version mentioned in Readme. Also, you can rewrite the code, if I remember correctly, the input dimension order of the tensor of torch.einsum or torch.pairwise_distance is changed in new version pytorch.
